create table random_people(
  first_name varchar(50),
  last_name varchar(50),
  email varchar(100)
);

select * 
from random_people;

delete from random_people;


insert into random_people(first_name, last_name, email)
with cte (first_name, last_name) as
(
  select 'Cordell', 'Shea' from dual union all 
  select 'Grant', 'Joyce' from dual union all 
  select 'Calvin', 'Clark' from dual union all 
  select 'Raymond', 'Snyder' from dual union all 
  select 'Darren', 'Oconnor' from dual union all 
  select 'Sean', 'Jones' from dual union all 
  select 'Jillian', 'Padilla' from dual union all 
  select 'Eleanor', 'Krueger' from dual union all 
  select 'Lidia', 'Murphy' from dual union all 
  select 'Hollis', 'Summers' from dual union all 
  select 'Sara', 'Oneal' from dual union all 
  select 'Garland', 'Price' from dual union all 
  select 'Florentino', 'Vega' from dual union all 
  select 'Faustino', 'Mooney' from dual union all 
  select 'Valarie', 'Costa' from dual union all 
  select 'Gino', 'Hamilton' from dual union all 
  select 'Karin', 'Bowen' from dual union all 
  select 'Hans', 'Sherman' from dual union all 
  select 'Tyler', 'Ortiz' from dual union all 
  select 'Gracie', 'Avery' from dual union all 
  select 'Brenton', 'Chapman' from dual union all 
  select 'Shelley', 'Buck' from dual union all 
  select 'Benita', 'Mcbride' from dual union all 
  select 'Omer', 'Roberts' from dual union all 
  select 'Pauline', 'Flores' from dual union all 
  select 'Elba', 'Hanna' from dual union all 
  select 'Janette', 'Cantrell' from dual union all 
  select 'Lucy', 'Pugh' from dual union all 
  select 'Carlo', 'Sharp' from dual union all 
  select 'Lottie', 'Escobar' from dual union all 
  select 'Rosemarie', 'Mclean' from dual union all 
  select 'Les', 'Dorsey' from dual union all 
  select 'Shirley', 'Porter' from dual union all 
  select 'Ezekiel', 'Hoover' from dual union all 
  select 'Adan', 'Burch' from dual union all 
  select 'Nell', 'Hogan' from dual union all 
  select 'Gavin', 'Lynn' from dual union all 
  select 'Rosa', 'Valdez' from dual union all 
  select 'Darius', 'Odom' from dual union all 
  select 'Pierre', 'Travis' from dual union all 
  select 'Christian', 'Tyler' from dual union all 
  select 'Leigh', 'Curtis' from dual union all 
  select 'Rebecca', 'Dalton' from dual union all 
  select 'Thomas', 'Wise' from dual union all 
  select 'Mia', 'Brady' from dual union all 
  select 'Emory', 'Fernandez' from dual union all 
  select 'Mariana', 'Ramirez' from dual union all 
  select 'Alfonzo', 'Case' from dual union all 
  select 'Darrick', 'Sexton' from dual union all 
  select 'Glenda', 'Campos' from dual union all 
  select 'Bridgette', 'Gilbert' from dual union all 
  select 'Norris', 'Mcneil' from dual union all 
  select 'Jerry', 'Hughes' from dual union all 
  select 'Sammie', 'Rocha' from dual union all 
  select 'Tania', 'Hawkins' from dual union all 
  select 'Sonya', 'Dunlap' from dual union all 
  select 'Noel', 'Morris' from dual union all 
  select 'Nora', 'Roman' from dual union all 
  select 'Loyd', 'Zamora' from dual union all 
  select 'Abraham', 'Barnett' from dual union all 
  select 'Nina', 'Newton' from dual union all 
  select 'Dorian', 'Potts' from dual union all 
  select 'Hai', 'Olsen' from dual union all 
  select 'Melanie', 'Bean' from dual union all 
  select 'Buster', 'Nolan' from dual union all 
  select 'Jeri', 'Lester' from dual union all 
  select 'Nathanial', 'Donaldson' from dual union all 
  select 'Dollie', 'Dillon' from dual union all 
  select 'Marva', 'Holloway' from dual union all 
  select 'Lupe', 'Dixon' from dual union all 
  select 'Dawn', 'Quinn' from dual union all 
  select 'Dixie', 'Lucero' from dual union all 
  select 'Nanette', 'Riggs' from dual union all 
  select 'Derek', 'Ball' from dual union all 
  select 'Jamie', 'Fry' from dual union all 
  select 'Brittany', 'Foley' from dual union all 
  select 'Sybil', 'Walters' from dual union all 
  select 'Karl', 'Meyers' from dual union all 
  select 'Lynnette', 'Harvey' from dual union all 
  select 'Scott', 'Meyer' from dual union all 
  select 'Raul', 'Hancock' from dual union all 
  select 'Wilda', 'Vasquez' from dual union all 
  select 'Yolanda', 'Gray' from dual union all 
  select 'Imogene', 'Huber' from dual union all 
  select 'Phoebe', 'Hernandez' from dual union all 
  select 'Josh', 'Rodgers' from dual union all 
  select 'Jc', 'Moran' from dual union all 
  select 'Sherry', 'Conner' from dual union all 
  select 'Arnulfo', 'Thompson' from dual union all 
  select 'Kristen', 'Sawyer' from dual union all 
  select 'Shelton', 'Sullivan' from dual union all 
  select 'Beulah', 'Cross' from dual union all 
  select 'Hester', 'Norman' from dual union all 
  select 'Effie', 'Larson' from dual union all 
  select 'Walter', 'Edwards' from dual union all 
  select 'Kenton', 'Mcmillan' from dual union all 
  select 'Nikki', 'Sheppard' from dual union all 
  select 'Octavio', 'Wiley' from dual union all 
  select 'Debbie', 'Rollins' from dual union all 
  select 'Hassan', 'Erickson' from dual union all 
  select 'Denver', 'Chan' from dual union all 
  select 'Sal', 'Combs' from dual union all 
  select 'Fred', 'Hahn' from dual union all 
  select 'Valentin', 'Maddox' from dual union all 
  select 'Branden', 'Osborn' from dual union all 
  select 'Allison', 'Day' from dual union all 
  select 'Chadwick', 'Park' from dual union all 
  select 'Delia', 'Hodges' from dual union all 
  select 'Lizzie', 'Webster' from dual union all 
  select 'Krista', 'Melton' from dual union all 
  select 'Laurie', 'Garcia' from dual union all 
  select 'Mallory', 'Kane' from dual union all 
  select 'Augusta', 'Casey' from dual union all 
  select 'August', 'Owen' from dual union all 
  select 'Vickie', 'Lowe' from dual union all 
  select 'Janell', 'Alvarado' from dual union all 
  select 'Elmo', 'Parrish' from dual union all 
  select 'Olive', 'Hess' from dual union all 
  select 'Miriam', 'Horne' from dual union all 
  select 'Mattie', 'Rasmussen' from dual union all 
  select 'Tasha', 'Montgomery' from dual union all 
  select 'Verna', 'Liu' from dual union all 
  select 'Marina', 'Walker' from dual union all 
  select 'Bernadine', 'Noble' from dual union all 
  select 'Melva', 'Carpenter' from dual union all 
  select 'Gilbert', 'Cummings' from dual union all 
  select 'Christopher', 'Lane' from dual union all 
  select 'Lamont', 'Smith' from dual union all 
  select 'Otis', 'Cooke' from dual union all 
  select 'Raleigh', 'Tran' from dual union all 
  select 'Deann', 'Gonzales' from dual union all 
  select 'Whitney', 'Schmidt' from dual union all 
  select 'Jannie', 'Orozco' from dual union all 
  select 'Dustin', 'Barrera' from dual union all 
  select 'Elliot', 'Leonard' from dual union all 
  select 'Kristopher', 'Middleton' from dual union all 
  select 'Everett', 'Hayden' from dual union all 
  select 'Bennett', 'Ho' from dual union all 
  select 'Jasper', 'Gutierrez' from dual union all 
  select 'Dewey', 'Gamble' from dual union all 
  select 'Natalia', 'Macdonald' from dual union all 
  select 'Chas', 'Butler' from dual union all 
  select 'Cedrick', 'Fox' from dual union all 
  select 'Leona', 'Rowland' from dual union all 
  select 'Barry', 'Christensen' from dual union all 
  select 'Valentine', 'Mckee' from dual union all 
  select 'Gilda', 'Frye' from dual union all 
  select 'Ahmed', 'Clements' from dual union all 
  select 'Debora', 'Trujillo' from dual union all 
  select 'Lawerence', 'Hartman' from dual union all 
  select 'Alton', 'Luna' from dual union all 
  select 'Efrain', 'Short' from dual union all 
  select 'Tanner', 'Paul' from dual union all 
  select 'Mervin', 'Baker' from dual union all 
  select 'Edgardo', 'Daugherty' from dual union all 
  select 'Solomon', 'Burgess' from dual union all 
  select 'Royal', 'Stokes' from dual union all 
  select 'Quincy', 'Villa' from dual union all 
  select 'Zack', 'Nelson' from dual union all 
  select 'Moshe', 'David' from dual union all 
  select 'Kathryn', 'Randall' from dual union all 
  select 'Ollie', 'Frank' from dual union all 
  select 'Willard', 'Benitez' from dual union all 
  select 'Cecilia', 'Mcguire' from dual union all 
  select 'Suzette', 'Shepherd' from dual union all 
  select 'Norman', 'Fitzgerald' from dual union all 
  select 'Maynard', 'Mendoza' from dual union all 
  select 'Estela', 'Herman' from dual union all 
  select 'Concepcion', 'Meadows' from dual union all 
  select 'Reuben', 'Cline' from dual union all 
  select 'Horace', 'Mccarty' from dual union all 
  select 'Katie', 'Lucas' from dual union all 
  select 'Reba', 'Werner' from dual union all 
  select 'Candace', 'Arroyo' from dual union all 
  select 'Rita', 'Kline' from dual union all 
  select 'Genevieve', 'Whitehead' from dual union all 
  select 'Vern', 'Blankenship' from dual union all 
  select 'Lula', 'Davies' from dual union all 
  select 'Debra', 'Stephenson' from dual union all 
  select 'Alan', 'Saunders' from dual union all 
  select 'Grace', 'Stone' from dual union all 
  select 'Reginald', 'Coleman' from dual union all 
  select 'Tristan', 'Graham' from dual union all 
  select 'Rickie', 'Salinas' from dual union all 
  select 'Darla', 'Flowers' from dual union all 
  select 'Kimberly', 'Burns' from dual union all 
  select 'Tyree', 'Lang' from dual union all 
  select 'Annie', 'Reese' from dual union all 
  select 'Angelica', 'Hopkins' from dual union all 
  select 'Long', 'Robles' from dual union all 
  select 'Sergio', 'Rose' from dual union all 
  select 'Rosella', 'Cohen' from dual union all 
  select 'Shaun', 'Bird' from dual union all 
  select 'Brandie', 'Harris' from dual union all 
  select 'Tony', 'Conway' from dual union all 
  select 'Wade', 'Yoder' from dual union all 
  select 'Robyn', 'Walton' from dual union all 
  select 'Ramona', 'Johns' from dual union all 
  select 'Lora', 'Moon' from dual union all 
  select 'Fern', 'Bonilla' from dual union all 
  select 'Francine', 'Wiggins' from dual union all 
  select 'Candy', 'Greer' from dual union all 
  select 'Howard', 'Crane' from dual union all 
  select 'Bennie', 'Phelps' from dual union all 
  select 'Stephen', 'Novak' from dual union all 
  select 'Robby', 'Reynolds' from dual union all 
  select 'Armand', 'Kirby' from dual union all 
  select 'Ramon', 'Pittman' from dual union all 
  select 'Rolf', 'Koch' from dual union all 
  select 'Nolan', 'Thomas' from dual union all 
  select 'Lynn', 'Duncan' from dual union all 
  select 'Bette', 'Savage' from dual union all 
  select 'Eli', 'Perry' from dual union all 
  select 'Kasey', 'Spence' from dual union all 
  select 'Doug', 'Willis' from dual union all 
  select 'Domingo', 'Yates' from dual union all 
  select 'Ross', 'Mason' from dual union all 
  select 'Seymour', 'Jackson' from dual union all 
  select 'Vance', 'Moody' from dual union all 
  select 'Colton', 'Mcgee' from dual union all 
  select 'Josephine', 'Lawrence' from dual union all 
  select 'Winnie', 'Kemp' from dual union all 
  select 'Leland', 'Calhoun' from dual union all 
  select 'Garfield', 'Howard' from dual union all 
  select 'Thad', 'Odonnell' from dual union all 
  select 'Belinda', 'Garrison' from dual union all 
  select 'Barbra', 'Vazquez' from dual union all 
  select 'Jodi', 'Suarez' from dual union all 
  select 'Blake', 'Booth' from dual union all 
  select 'Lanny', 'Levy' from dual union all 
  select 'Fausto', 'Flynn' from dual union all 
  select 'Katherine', 'Mcdonald' from dual union all 
  select 'Rosie', 'Carey' from dual union all 
  select 'Randal', 'Baldwin' from dual union all 
  select 'Stephanie', 'Berry' from dual union all 
  select 'Stanford', 'Knapp' from dual union all 
  select 'Lucien', 'Lara' from dual union all 
  select 'Mari', 'Nash' from dual union all 
  select 'Efren', 'Le' from dual union all 
  select 'Tina', 'Lloyd' from dual union all 
  select 'Angelita', 'Prince' from dual union all 
  select 'Juanita', 'Lindsey' from dual union all 
  select 'Zane', 'Byrd' from dual union all 
  select 'Sam', 'Levine' from dual union all 
  select 'Roberta', 'Gilmore' from dual union all 
  select 'Irene', 'Woodard' from dual union all 
  select 'Socorro', 'Ray' from dual union all 
  select 'Rudolf', 'Charles' from dual union all 
  select 'Gene', 'Douglas' from dual union all 
  select 'Leroy', 'Watson' from dual union all 
  select 'Mandy', 'Mathis' from dual union all 
  select 'Greg', 'Ross' from dual union all 
  select 'Brigitte', 'Ellison' from dual union all 
  select 'Irma', 'Mcgrath' from dual union all 
  select 'Isidro', 'Ryan' from dual union all 
  select 'Owen', 'Rojas' from dual union all 
  select 'Cedric', 'Lopez' from dual union all 
  select 'Lucas', 'Mccormick' from dual union all 
  select 'Bruno', 'Oneill' from dual union all 
  select 'Neil', 'Rivas' from dual union all 
  select 'Brittney', 'Carlson' from dual union all 
  select 'Deena', 'Bernard' from dual union all 
  select 'Flossie', 'Wall' from dual union all 
  select 'Bertram', 'Best' from dual union all 
  select 'Luann', 'Barnes' from dual union all 
  select 'Adolph', 'Garner' from dual union all 
  select 'Madeleine', 'Trevino' from dual union all 
  select 'Annette', 'Bright' from dual union all 
  select 'Aline', 'Woodward' from dual union all 
  select 'Nettie', 'Brennan' from dual union all 
  select 'Susanna', 'Gallegos' from dual union all 
  select 'Harriett', 'Baxter' from dual union all 
  select 'Boyd', 'Clayton' from dual union all 
  select 'Stevie', 'Hardy' from dual union all 
  select 'Jeramy', 'Becker' from dual union all 
  select 'Jordan', 'Soto' from dual union all 
  select 'Patti', 'Castaneda' from dual union all 
  select 'Taylor', 'Archer' from dual union all 
  select 'Deloris', 'Bowers' from dual union all 
  select 'Arnoldo', 'Figueroa' from dual union all 
  select 'Aileen', 'Aguirre' from dual union all 
  select 'Concetta', 'Turner' from dual union all 
  select 'Coy', 'Lowery' from dual union all 
  select 'Ofelia', 'Beltran' from dual union all 
  select 'Lana', 'Long' from dual union all 
  select 'Korey', 'Gibson' from dual union all 
  select 'Roseann', 'Sellers' from dual union all 
  select 'Mckinley', 'Ewing' from dual union all 
  select 'Arlene', 'Hensley' from dual union all 
  select 'Alisha', 'Blackwell' from dual union all 
  select 'Alissa', 'Henson' from dual union all 
  select 'Ed', 'Mann' from dual union all 
  select 'Jamar', 'Chandler' from dual union all 
  select 'Clara', 'Cook' from dual union all 
  select 'Amos', 'Weiss' from dual union all 
  select 'Rusty', 'Adams' from dual union all 
  select 'Beatriz', 'Hale' from dual union all 
  select 'Mason', 'Solis' from dual union all 
  select 'Toni', 'Burton' from dual union all 
  select 'Elliott', 'Carson' from dual union all 
  select 'Reinaldo', 'Drake' from dual union all 
  select 'Lazaro', 'Andrade' from dual union all 
  select 'Ella', 'Delgado' from dual union all 
  select 'Bruce', 'Gentry' from dual union all 
  select 'Hunter', 'Knight' from dual union all 
  select 'Michele', 'Schroeder' from dual union all 
  select 'Lorenzo', 'Gross' from dual union all 
  select 'Berry', 'Cisneros' from dual union all 
  select 'Chester', 'Cortez' from dual union all 
  select 'Casey', 'Hubbard' from dual union all 
  select 'Jacinto', 'Richmond' from dual union all 
  select 'Nannie', 'Bentley' from dual union all 
  select 'Tyrone', 'Villanueva' from dual union all 
  select 'Henry', 'Colon' from dual union all 
  select 'Nadia', 'Pitts' from dual union all 
  select 'Yesenia', 'Huang' from dual union all 
  select 'Martina', 'Peterson' from dual union all 
  select 'Alyssa', 'Pollard' from dual union all 
  select 'Rosendo', 'Ponce' from dual union all 
  select 'Emilio', 'Bowman' from dual union all 
  select 'Lydia', 'Mueller' from dual union all 
  select 'Kristy', 'Ballard' from dual union all 
  select 'Lillian', 'Parsons' from dual union all 
  select 'Dwain', 'Pearson' from dual union all 
  select 'Noemi', 'Pace' from dual union all 
  select 'Jarrett', 'Barron' from dual union all 
  select 'Marcia', 'Branch' from dual union all 
  select 'Chung', 'Morgan' from dual union all 
  select 'Tory', 'Nielsen' from dual union all 
  select 'Clifton', 'Pineda' from dual union all 
  select 'Lenny', 'Snow' from dual union all 
  select 'Camille', 'Salas' from dual union all 
  select 'Maryellen', 'Benson' from dual union all 
  select 'Jeffry', 'Gillespie' from dual union all 
  select 'Ines', 'Humphrey' from dual union all 
  select 'Delmar', 'Holmes' from dual union all 
  select 'Ariel', 'Klein' from dual union all 
  select 'Bobbi', 'Chavez' from dual union all 
  select 'Hobert', 'Gould' from dual union all 
  select 'Willa', 'Barry' from dual union all 
  select 'Fabian', 'Diaz' from dual union all 
  select 'Carlos', 'Mercado' from dual union all 
  select 'Hilton', 'Love' from dual union all 
  select 'Bertie', 'Mata' from dual union all 
  select 'Malinda', 'Dickerson' from dual union all 
  select 'Jefferson', 'Holland' from dual union all 
  select 'Penelope', 'Brock' from dual union all 
  select 'Terri', 'Mora' from dual union all 
  select 'Jeff', 'Sanford' from dual union all 
  select 'Valeria', 'Riley' from dual union all 
  select 'Sanford', 'Rivers' from dual union all 
  select 'Phyllis', 'Owens' from dual union all 
  select 'Milagros', 'Alexander' from dual union all 
  select 'Buford', 'Romero' from dual union all 
  select 'Cindy', 'Mccarthy' from dual union all 
  select 'Shayne', 'Welch' from dual union all 
  select 'Fletcher', 'Munoz' from dual union all 
  select 'Vito', 'Wells' from dual union all 
  select 'June', 'Ochoa' from dual union all 
  select 'Leann', 'Schwartz' from dual union all 
  select 'Ernestine', 'Church' from dual union all 
  select 'Wilber', 'Heath' from dual union all 
  select 'Alicia', 'Stanton' from dual union all 
  select 'Francis', 'Cannon' from dual union all 
  select 'Madeline', 'Villegas' from dual union all 
  select 'Lawanda', 'Marquez' from dual union all 
  select 'Gaston', 'Davidson' from dual union all 
  select 'Krystal', 'Murillo' from dual union all 
  select 'Marion', 'Pierce' from dual union all 
  select 'Jonas', 'Berger' from dual union all 
  select 'Jere', 'Key' from dual union all 
  select 'Bradley', 'Morrow' from dual union all 
  select 'Cheryl', 'Norton' from dual union all 
  select 'Frances', 'Strickland' from dual union all 
  select 'Cliff', 'Chaney' from dual union all 
  select 'Isabella', 'Hurley' from dual union all 
  select 'Liz', 'Leblanc' from dual union all 
  select 'Madelyn', 'Harrington' from dual union all 
  select 'Bert', 'Cardenas' from dual union all 
  select 'Duncan', 'Orr' from dual union all 
  select 'Rebekah', 'Williamson' from dual union all 
  select 'Tanisha', 'Hart' from dual union all 
  select 'Brooks', 'Schultz' from dual union all 
  select 'Autumn', 'Stephens' from dual union all 
  select 'Pam', 'Velez' from dual union all 
  select 'Carl', 'Mcmahon' from dual union all 
  select 'Leopoldo', 'Larsen' from dual union all 
  select 'Teresa', 'Hickman' from dual union all 
  select 'Gregory', 'Andersen' from dual union all 
  select 'Fermin', 'Powers' from dual union all 
  select 'Alyson', 'Wheeler' from dual union all 
  select 'Casandra', 'Mccoy' from dual union all 
  select 'Lea', 'Hobbs' from dual union all 
  select 'Tammi', 'York' from dual union all 
  select 'Mac', 'Bridges' from dual union all 
  select 'Trevor', 'Mcintyre' from dual union all 
  select 'Hugh', 'Morales' from dual union all 
  select 'Timmy', 'Bass' from dual union all 
  select 'Mark', 'Strong' from dual union all 
  select 'Noreen', 'Carrillo' from dual union all 
  select 'Shelby', 'Griffith' from dual union all 
  select 'Marc', 'Huerta' from dual union all 
  select 'Meagan', 'Good' from dual union all 
  select 'Philip', 'English' from dual union all 
  select 'Aimee', 'Silva' from dual union all 
  select 'Juliet', 'Solomon' from dual union all 
  select 'Malcolm', 'Townsend' from dual union all 
  select 'Brandon', 'Young' from dual union all 
  select 'Maude', 'Cuevas' from dual union all 
  select 'Yvette', 'Lozano' from dual union all 
  select 'Ezra', 'Zuniga' from dual union all 
  select 'Rick', 'Hodge' from dual union all 
  select 'Floyd', 'Velasquez' from dual union all 
  select 'Penny', 'Hutchinson' from dual union all 
  select 'Maria', 'Zhang' from dual union all 
  select 'Warner', 'Nixon' from dual union all 
  select 'Tommie', 'Austin' from dual union all 
  select 'Ashley', 'Robinson' from dual union all 
  select 'Kirby', 'Raymond' from dual union all 
  select 'Vicki', 'Santana' from dual union all 
  select 'Antone', 'Higgins' from dual union all 
  select 'Rico', 'Cooper' from dual union all 
  select 'Joseph', 'West' from dual union all 
  select 'Nicky', 'Shaw' from dual union all 
  select 'Catalina', 'Perez' from dual union all 
  select 'Morris', 'Nichols' from dual union all 
  select 'Dorsey', 'Hanson' from dual union all 
  select 'Marianne', 'Dennis' from dual union all 
  select 'Johnathon', 'Acosta' from dual union all 
  select 'Antonio', 'Ramsey' from dual union all 
  select 'Elena', 'Spencer' from dual union all 
  select 'Phillip', 'Jacobson' from dual union all 
  select 'Kenny', 'Mayer' from dual union all 
  select 'Tamika', 'Lamb' from dual union all 
  select 'Adeline', 'Decker' from dual union all 
  select 'Chance', 'Doyle' from dual union all 
  select 'Thelma', 'Torres' from dual union all 
  select 'Patrice', 'Hebert' from dual union all 
  select 'Graciela', 'Harper' from dual union all 
  select 'Billie', 'Reyes' from dual union all 
  select 'Emmanuel', 'Baird' from dual union all 
  select 'Johanna', 'Eaton' from dual union all 
  select 'Jerrell', 'Zimmerman' from dual union all 
  select 'Laverne', 'Lutz' from dual union all 
  select 'Margaret', 'Mendez' from dual union all 
  select 'Keith', 'Preston' from dual union all 
  select 'Angelo', 'Forbes' from dual union all 
  select 'Theo', 'Grant' from dual union all 
  select 'Craig', 'Oconnell' from dual union all 
  select 'Alexandria', 'Simon' from dual union all 
  select 'Cristopher', 'Bradshaw' from dual union all 
  select 'Deirdre', 'Medina' from dual union all 
  select 'Amie', 'Chang' from dual union all 
  select 'Elmer', 'Mcpherson' from dual union all 
  select 'Kristi', 'Fields' from dual union all 
  select 'Paulette', 'Warren' from dual union all 
  select 'Lou', 'Yu' from dual union all 
  select 'Christi', 'Gardner' from dual union all 
  select 'Amy', 'Ibarra' from dual union all 
  select 'Billy', 'Everett' from dual union all 
  select 'Lamar', 'Glover' from dual union all 
  select 'Adolfo', 'Grimes' from dual union all 
  select 'Deangelo', 'Mckenzie' from dual union all 
  select 'Liza', 'Duarte' from dual union all 
  select 'Shari', 'Chambers' from dual union all 
  select 'Sylvester', 'Durham' from dual union all 
  select 'Dexter', 'Marks' from dual union all 
  select 'Perry', 'Patrick' from dual union all 
  select 'Elias', 'Miller' from dual union all 
  select 'Osvaldo', 'Underwood' from dual union all 
  select 'Trinidad', 'Mays' from dual union all 
  select 'Lina', 'Leon' from dual union all 
  select 'Selma', 'Boyer' from dual union all 
  select 'Nola', 'Wilson' from dual union all 
  select 'Terrance', 'Sims' from dual union all 
  select 'Refugio', 'Conley' from dual union all 
  select 'Silvia', 'Knox' from dual union all 
  select 'Amelia', 'Blackburn' from dual union all 
  select 'Peggy', 'Keith' from dual union all 
  select 'Manuel', 'Palmer' from dual union all 
  select 'Joyce', 'Franco' from dual union all 
  select 'Muriel', 'Todd' from dual union all 
  select 'Josef', 'Stark' from dual union all 
  select 'Hong', 'House' from dual union all 
  select 'Cruz', 'Santos' from dual union all 
  select 'Edward', 'Singh' from dual union all 
  select 'Eugenia', 'Clarke' from dual union all 
  select 'Jerri', 'Cain' from dual union all 
  select 'Danielle', 'Rush' from dual union all 
  select 'Gerardo', 'Pruitt' from dual union all 
  select 'Rocky', 'Frederick' from dual union all 
  select 'Clark', 'Webb' from dual union all 
  select 'Danilo', 'Schaefer' from dual union all 
  select 'Orville', 'Beard' from dual union all 
  select 'Kerri', 'Bennett' from dual union all 
  select 'Ruthie', 'Myers' from dual union all 
  select 'Roman', 'Riddle' from dual union all 
  select 'Maurice', 'Mcknight' from dual union all 
  select 'Demarcus', 'Hurst' from dual union all 
  select 'Donte', 'Vaughn' from dual union all 
  select 'Maxine', 'Bishop' from dual union all 
  select 'Alfreda', 'Nunez' from dual union all 
  select 'Jayson', 'Callahan' from dual union all 
  select 'Lilly', 'Parker' from dual union all 
  select 'Magdalena', 'Randolph' from dual union all 
  select 'Lynwood', 'Marshall' from dual union all 
  select 'Eduardo', 'Logan' from dual union all 
  select 'Clarice', 'Lambert' from dual union all 
  select 'Jesus', 'Phillips' from dual union all 
  select 'Amanda', 'Morse' from dual union all 
  select 'Noah', 'Lam' from dual union all 
  select 'Louisa', 'Fisher' from dual union all 
  select 'Ellsworth', 'Curry' from dual union all 
  select 'Winston', 'Buchanan' from dual union all 
  select 'Everette', 'Browning' from dual union all 
  select 'Tamra', 'Jennings' from dual union all 
  select 'Shane', 'Huynh' from dual union all 
  select 'Meredith', 'Brandt' from dual union all 
  select 'Zachery', 'Peters' from dual union all 
  select 'Odessa', 'Bryant' from dual union all 
  select 'Wilburn', 'Mills' from dual union all 
  select 'Winford', 'Kramer' from dual union all 
  select 'Albert', 'Patterson' from dual union all 
  select 'Rodger', 'Goodman' from dual union all 
  select 'Clair', 'Benton' from dual union all 
  select 'Norbert', 'Watkins' from dual union all 
  select 'Freddie', 'Serrano' from dual union all 
  select 'Orval', 'Jenkins' from dual union all 
  select 'Werner', 'Valencia' from dual union all 
  select 'Riley', 'Haynes' from dual union all 
  select 'Conrad', 'Potter' from dual union all 
  select 'Noe', 'Juarez' from dual union all 
  select 'Forrest', 'Duffy' from dual union all 
  select 'Vicente', 'Reid' from dual union all 
  select 'Luz', 'French' from dual union all 
  select 'Greta', 'Hansen' from dual union all 
  select 'Sheldon', 'Horn' from dual union all 
  select 'Oscar', 'Reeves' from dual union all 
  select 'Ian', 'Armstrong' from dual union all 
  select 'Ginger', 'Mullins' from dual union all 
  select 'Leandro', 'Richard' from dual union all 
  select 'Andreas', 'Cordova' from dual union all 
  select 'Nellie', 'Craig' from dual union all 
  select 'Shauna', 'Russo' from dual union all 
  select 'Leah', 'Harrison' from dual union all 
  select 'Beau', 'Ferrell' from dual union all 
  select 'Margo', 'Mahoney' from dual union all 
  select 'Stanley', 'Maynard' from dual union all 
  select 'Mamie', 'Elliott' from dual union all 
  select 'Josefa', 'Cox' from dual union all 
  select 'Emerson', 'Buckley' from dual union all 
  select 'Lauren', 'Floyd' from dual union all 
  select 'Tara', 'Neal' from dual union all 
  select 'Gena', 'Evans' from dual union all 
  select 'Jenna', 'Moore' from dual union all 
  select 'Donna', 'Rich' from dual union all 
  select 'Fay', 'Terry' from dual union all 
  select 'Elvira', 'Hudson' from dual union all 
  select 'Dino', 'Glass' from dual union all 
  select 'Gerald', 'Kirk' from dual union all 
  select 'Santiago', 'Anderson' from dual union all 
  select 'Anton', 'Cherry' from dual union all 
  select 'Marissa', 'Madden' from dual union all 
  select 'Dianne', 'Mosley' from dual union all 
  select 'Kermit', 'Faulkner' from dual union all 
  select 'Darnell', 'Merritt' from dual union all 
  select 'Katharine', 'Hoffman' from dual union all 
  select 'Donnie', 'Boyle' from dual union all 
  select 'Errol', 'Davis' from dual union all 
  select 'Kieth', 'Vance' from dual union all 
  select 'Chuck', 'Kent' from dual union all 
  select 'Roxie', 'Griffin' from dual union all 
  select 'Josie', 'Valenzuela' from dual union all 
  select 'Jamison', 'Beasley' from dual union all 
  select 'Tonia', 'Herring' from dual union all 
  select 'Renato', 'Tanner' from dual union all 
  select 'Nancy', 'Dougherty' from dual union all 
  select 'Kyle', 'Monroe' from dual union all 
  select 'Rufus', 'Giles' from dual union all 
  select 'Dean', 'Cantu' from dual union all 
  select 'Troy', 'Patton' from dual union all 
  select 'Harriet', 'Jefferson' from dual union all 
  select 'Dusty', 'Mullen' from dual union all 
  select 'Cheri', 'Anthony' from dual union all 
  select 'Shanna', 'Caldwell' from dual union all 
  select 'Tia', 'Bolton' from dual union all 
  select 'May', 'Rubio' from dual union all 
  select 'Melissa', 'Hull' from dual union all 
  select 'Fredric', 'Wilkerson' from dual union all 
  select 'Terence', 'Guzman' from dual union all 
  select 'Elden', 'Rios' from dual union all 
  select 'Josiah', 'Schneider' from dual union all 
  select 'Enid', 'Kerr' from dual union all 
  select 'Brock', 'Blanchard' from dual union all 
  select 'Augustine', 'Gonzalez' from dual union all 
  select 'Scotty', 'Braun' from dual union all 
  select 'Nicholas', 'Galvan' from dual union all 
  select 'Rex', 'Gomez' from dual union all 
  select 'Lynda', 'Ali' from dual union all 
  select 'Bill', 'Donovan' from dual union all 
  select 'Mona', 'Burke' from dual union all 
  select 'Carlene', 'Hall' from dual union all 
  select 'Hiram', 'Ellis' from dual union all 
  select 'Celina', 'Skinner' from dual union all 
  select 'Betsy', 'Beck' from dual union all 
  select 'Eusebio', 'Vargas' from dual union all 
  select 'Nicolas', 'Jarvis' from dual union all 
  select 'Rosalyn', 'Sampson' from dual union all 
  select 'Lori', 'Tapia' from dual union all 
  select 'Nichole', 'Stout' from dual union all 
  select 'Elton', 'Acevedo' from dual union all 
  select 'Minnie', 'Glenn' from dual union all 
  select 'Dwayne', 'Bartlett' from dual union all 
  select 'Deanne', 'Farrell' from dual union all 
  select 'Abby', 'Wong' from dual union all 
  select 'Chelsea', 'Wu' from dual union all 
  select 'Sophie', 'Dudley' from dual union all 
  select 'Arline', 'Hunter' from dual union all 
  select 'Frieda', 'Sweeney' from dual union all 
  select 'Marylou', 'Farmer' from dual union all 
  select 'Bessie', 'Castillo' from dual union all 
  select 'Tyson', 'Jordan' from dual union all 
  select 'Kris', 'Richards' from dual union all 
  select 'Garret', 'Espinoza' from dual union all 
  select 'Odis', 'Roy' from dual union all 
  select 'Tammie', 'Landry' from dual union all 
  select 'Loren', 'Bates' from dual union all 
  select 'Adrian', 'Richardson' from dual union all 
  select 'Sasha', 'Bailey' from dual union all 
  select 'Julio', 'Hendrix' from dual union all 
  select 'Wendell', 'Golden' from dual union all 
  select 'David', 'Ayala' from dual union all 
  select 'Louie', 'Morton' from dual union all 
  select 'Luther', 'Shelton' from dual union all 
  select 'Marlin', 'Bautista' from dual union all 
  select 'Hallie', 'Guerrero' from dual union all 
  select 'Olivia', 'Hinton' from dual union all 
  select 'Marcel', 'Dominguez' from dual union all 
  select 'Mayra', 'Bush' from dual union all 
  select 'Samuel', 'Joseph' from dual union all 
  select 'Thanh', 'Atkinson' from dual union all 
  select 'Erwin', 'Mcconnell' from dual union all 
  select 'Maryanne', 'Cabrera' from dual union all 
  select 'Agnes', 'Gay' from dual union all 
  select 'Ali', 'Hammond' from dual union all 
  select 'Earl', 'Simpson' from dual union all 
  select 'Lawrence', 'Howe' from dual union all 
  select 'Gayle', 'Wade' from dual union all 
  select 'Randy', 'Whitney' from dual union all 
  select 'Daniel', 'Bullock' from dual union all 
  select 'Bridget', 'Hooper' from dual union all 
  select 'Maximo', 'Hatfield' from dual union all 
  select 'Georgina', 'Wood' from dual union all 
  select 'Elise', 'Houston' from dual union all 
  select 'Barbara', 'Weeks' from dual union all 
  select 'Carey', 'Weaver' from dual union all 
  select 'Bobby', 'Barajas' from dual union all 
  select 'Theron', 'Hood' from dual union all 
  select 'Jill', 'Holder' from dual union all 
  select 'Marie', 'Bruce' from dual union all 
  select 'Darcy', 'Stanley' from dual union all 
  select 'Dianna', 'Montes' from dual union all 
  select 'Darryl', 'Carroll' from dual union all 
  select 'Nelda', 'Frey' from dual union all 
  select 'Roderick', 'Hicks' from dual union all 
  select 'Darell', 'Goodwin' from dual union all 
  select 'Cary', 'Bender' from dual union all 
  select 'Kraig', 'Keller' from dual union all 
  select 'Lillie', 'Rowe' from dual union all 
  select 'Truman', 'Wang' from dual union all 
  select 'Rickey', 'Parks' from dual union all 
  select 'Alec', 'Krause' from dual union all 
  select 'Martin', 'Briggs' from dual union all 
  select 'Joanna', 'Villarreal' from dual union all 
  select 'Abel', 'Jacobs' from dual union all 
  select 'Iva', 'Castro' from dual union all 
  select 'Jamal', 'Spears' from dual union all 
  select 'Brant', 'Olson' from dual union all 
  select 'Essie', 'Singleton' from dual union all 
  select 'Darrin', 'Cowan' from dual union all 
  select 'Kimberley', 'Waters' from dual union all 
  select 'Joey', 'Allen' from dual union all 
  select 'Jaclyn', 'Pratt' from dual union all 
  select 'Luke', 'Dodson' from dual union all 
  select 'Jon', 'Holden' from dual union all 
  select 'Blanche', 'Steele' from dual union all 
  select 'Lauri', 'Gordon' from dual union all 
  select 'Edwina', 'Rhodes' from dual union all 
  select 'Emily', 'Brown' from dual union all 
  select 'Michael', 'Rosales' from dual union all 
  select 'Priscilla', 'Arellano' from dual union all 
  select 'Neville', 'Wright' from dual union all 
  select 'Dick', 'Lawson' from dual union all 
  select 'Wilma', 'Leach' from dual union all 
  select 'Kay', 'Dyer' from dual union all 
  select 'Freida', 'Kaufman' from dual union all 
  select 'Marcus', 'Sanders' from dual union all 
  select 'Benjamin', 'Woods' from dual union all 
  select 'Isaac', 'Rogers' from dual union all 
  select 'Tod', 'Cole' from dual union all 
  select 'Enoch', 'Christian' from dual union all 
  select 'Ethel', 'Holt' from dual union all 
  select 'Avis', 'Harding' from dual union all 
  select 'Eugenio', 'Collins' from dual union all 
  select 'Jewell', 'Walsh' from dual union all 
  select 'Myles', 'Mccullough' from dual union all 
  select 'Terrie', 'Lee' from dual union all 
  select 'Dorothea', 'Cobb' from dual union all 
  select 'Malcom', 'Washington' from dual union all 
  select 'Eddie', 'Lynch' from dual union all 
  select 'Morgan', 'Martinez' from dual union all 
  select 'Katelyn', 'Wilkinson' from dual union all 
  select 'William', 'Barker' from dual union all 
  select 'Ellis', 'Maldonado' from dual union all 
  select 'Justine', 'Howell' from dual union all 
  select 'Nita', 'Mcdowell' from dual union all 
  select 'Frederick', 'Nguyen' from dual union all 
  select 'Edgar', 'Wilkins' from dual union all 
  select 'Ashlee', 'Kelly' from dual union all 
  select 'Lacy', 'Davenport' from dual union all 
  select 'Ben', 'Petty' from dual union all 
  select 'Helga', 'Ford' from dual union all 
  select 'Reyna', 'Deleon' from dual union all 
  select 'Allyson', 'Little' from dual union all 
  select 'Darlene', 'Warner' from dual union all 
  select 'Lindsey', 'Moyer' from dual union all 
  select 'Shelia', 'Brooks' from dual union all 
  select 'Constance', 'Hines' from dual union all 
  select 'Rogelio', 'Blake' from dual union all 
  select 'Rashad', 'Johnston' from dual union all 
  select 'Israel', 'Freeman' from dual union all 
  select 'Walker', 'Harrell' from dual union all 
  select 'Mohammed', 'Rosario' from dual union all 
  select 'Rosalind', 'Mathews' from dual union all 
  select 'Moses', 'Haney' from dual union all 
  select 'Hillary', 'Shah' from dual union all 
  select 'Mabel', 'Dickson' from dual union all 
  select 'Ken', 'Russell' from dual union all 
  select 'Landon', 'Tate' from dual union all 
  select 'Cesar', 'Cochran' from dual union all 
  select 'Samual', 'Duran' from dual union all 
  select 'Joanne', 'Galloway' from dual union all 
  select 'Pearl', 'Newman' from dual union all 
  select 'Johnny', 'Mcfarland' from dual union all 
  select 'Judith', 'Peck' from dual union all 
  select 'Earnestine', 'Rodriguez' from dual union all 
  select 'Trisha', 'Choi' from dual union all 
  select 'Brain', 'Hendricks' from dual union all 
  select 'Susie', 'Swanson' from dual union all 
  select 'Nickolas', 'Thornton' from dual union all 
  select 'Horacio', 'Finley' from dual union all 
  select 'Reyes', 'Graves' from dual union all 
  select 'Clarissa', 'Bauer' from dual union all 
  select 'Jospeh', 'Yang' from dual union all 
  select 'Rodrigo', 'Hays' from dual union all 
  select 'Virginia', 'Barrett' from dual union all 
  select 'Leif', 'Kelley' from dual union all 
  select 'Eric', 'Reilly' from dual union all 
  select 'Jasmine', 'Bell' from dual union all 
  select 'Carmela', 'Greene' from dual union all 
  select 'Polly', 'Santiago' from dual union all 
  select 'Van', 'Patel' from dual union all 
  select 'Robt', 'Kidd' from dual union all 
  select 'Annabelle', 'Reed' from dual union all 
  select 'Bettie', 'George' from dual union all 
  select 'Arron', 'Proctor' from dual union all 
  select 'Edwardo', 'King' from dual union all 
  select 'Maricela', 'Walls' from dual union all 
  select 'Violet', 'Pope' from dual union all 
  select 'Elroy', 'Miles' from dual union all 
  select 'Deandre', 'Daniel' from dual union all 
  select 'Santos', 'Whitaker' from dual union all 
  select 'Andre', 'Montoya' from dual union all 
  select 'Mickey', 'Mcdaniel' from dual union all 
  select 'Nigel', 'Cunningham' from dual union all 
  select 'Kurt', 'Sandoval' from dual union all 
  select 'Evelyn', 'Lewis' from dual union all 
  select 'Ruby', 'Barton' from dual union all 
  select 'Alexandra', 'Li' from dual union all 
  select 'Georgia', 'Collier' from dual union all 
  select 'Johnathan', 'Powell' from dual union all 
  select 'Guillermo', 'Bryan' from dual union all 
  select 'Louise', 'Henry' from dual union all 
  select 'Bryan', 'Crosby' from dual union all 
  select 'Lester', 'Mayo' from dual union all 
  select 'Misty', 'Garrett' from dual union all 
  select 'Rhonda', 'Page' from dual union all 
  select 'Clyde', 'Ortega' from dual union all 
  select 'Sol', 'Hampton' from dual union all 
  select 'Margie', 'Mccall' from dual union all 
  select 'Bonita', 'Guerra' from dual union all 
  select 'Marlene', 'Livingston' from dual union all 
  select 'Linda', 'Abbott' from dual union all 
  select 'Susan', 'Watts' from dual union all 
  select 'Marcella', 'Franklin' from dual union all 
  select 'Nathaniel', 'Dean' from dual union all 
  select 'Paige', 'Winters' from dual union all 
  select 'Lance', 'White' from dual union all 
  select 'Deana', 'Wallace' from dual union all 
  select 'Jerome', 'Molina' from dual union all 
  select 'Corinne', 'Stafford' from dual union all 
  select 'Jami', 'Scott' from dual union all 
  select 'Hattie', 'Huffman' from dual union all 
  select 'Fredrick', 'Black' from dual union all 
  select 'Andrew', 'Campbell' from dual union all 
  select 'Seth', 'Mckinney' from dual union all 
  select 'Monte', 'Michael' from dual union all 
  select 'Emilia', 'Mclaughlin' from dual union all 
  select 'Tom', 'Salazar' from dual union all 
  select 'Erma', 'Fischer' from dual union all 
  select 'Corina', 'Ritter' from dual union all 
  select 'Catherine', 'Pennington' from dual union all 
  select 'Evan', 'Andrews' from dual union all 
  select 'Loretta', 'Melendez' from dual union all 
  select 'Buck', 'Crawford' from dual union all 
  select 'Karyn', 'Sanchez' from dual union all 
  select 'Faye', 'Weber' from dual union all 
  select 'Larry', 'Booker' from dual union all 
  select 'Virgilio', 'Ware' from dual union all 
  select 'Rod', 'Williams' from dual union all 
  select 'Ernie', 'Dawson' from dual union all 
  select 'Pablo', 'Malone' from dual union all 
  select 'Murray', 'Haley' from dual union all 
  select 'Kate', 'Mack' from dual union all 
  select 'Ervin', 'Mcclure' from dual union all 
  select 'Brooke', 'Frost' from dual union all 
  select 'Hayden', 'Garza' from dual union all 
  select 'Christoper', 'Rangel' from dual union all 
  select 'Norma', 'Wolf' from dual union all 
  select 'Teri', 'Boyd' from dual union all 
  select 'Will', 'James' from dual union all 
  select 'Zachariah', 'Mccann' from dual union all 
  select 'Adele', 'Meza' from dual union all 
  select 'Bernie', 'Obrien' from dual union all 
  select 'Sterling', 'Bray' from dual union all 
  select 'Cole', 'Irwin' from dual union all 
  select 'Hank', 'Vincent' from dual union all 
  select 'Ray', 'Mcclain' from dual union all 
  select 'Arnold', 'Massey' from dual union all 
  select 'Josefina', 'Sosa' from dual union all 
  select 'Sheryl', 'Alvarez' from dual union all 
  select 'Victor', 'Harmon' from dual union all 
  select 'Maureen', 'Avila' from dual union all 
  select 'Neva', 'Camacho' from dual union all 
  select 'Lesley', 'Stein' from dual union all 
  select 'Antwan', 'Ayers' from dual union all 
  select 'Santo', 'Schmitt' from dual union all 
  select 'Antione', 'Frazier' from dual union all 
  select 'Ty', 'Shields' from dual union all 
  select 'Ronny', 'Fitzpatrick' from dual union all 
  select 'Tracey', 'Chen' from dual union all 
  select 'Sonny', 'Boone' from dual union all 
  select 'Dalton', 'Zavala' from dual union all 
  select 'Sherri', 'Small' from dual union all 
  select 'Dwight', 'Mercer' from dual union all 
  select 'Jeremy', 'Valentine' from dual union all 
  select 'Ulysses', 'Sutton' from dual union all 
  select 'Sheena', 'Gregory' from dual union all 
  select 'Kelly', 'Murray' from dual union all 
  select 'Spencer', 'Duke' from dual union all 
  select 'Consuelo', 'Ashley' from dual union all 
  select 'Meghan', 'Vaughan' from dual union all 
  select 'Cyrus', 'Fowler' from dual union all 
  select 'Norberto', 'Ferguson' from dual union all 
  select 'Ivan', 'Burnett' from dual union all 
  select 'Alberto', 'Fleming' from dual union all 
  select 'Alonzo', 'Blevins' from dual union all 
  select 'Pansy', 'Fuller' from dual union all 
  select 'Raphael', 'Carr' from dual union all 
  select 'Vincenzo', 'Martin' from dual union all 
  select 'Alexis', 'Mcintosh' from dual union all 
  select 'Dewitt', 'Norris' from dual union all 
  select 'Arden', 'Arnold' from dual union all 
  select 'Davis', 'Pacheco' from dual union all 
  select 'Humberto', 'Bradford' from dual union all 
  select 'Galen', 'Johnson' from dual union all 
  select 'Diann', 'Dunn' from dual union all 
  select 'Cody', 'Herrera' from dual union all 
  select 'Justin', 'Shaffer' from dual union all 
  select 'Lonnie', 'Nicholson' from dual union all 
  select 'Isabel', 'Gallagher' from dual union all 
  select 'Nick', 'Francis' from dual union all 
  select 'Dena', 'Sparks' from dual union all 
  select 'Cathy', 'Carney' from dual union all 
  select 'Sandra', 'Velazquez' from dual union all 
  select 'Rae', 'Ward' from dual union all 
  select 'Elvin', 'Haas' from dual union all 
  select 'Willy', 'Foster' from dual union all 
  select 'Herbert', 'Aguilar' from dual union all 
  select 'Lenard', 'Hill' from dual union all 
  select 'Charlotte', 'Calderon' from dual union all 
  select 'Lewis', 'Friedman' from dual union all 
  select 'Janine', 'Gill' from dual union all 
  select 'Frank', 'Cruz' from dual union all 
  select 'Jed', 'Hayes' from dual union all 
  select 'Jesse', 'Robertson' from dual union all 
  select 'Randall', 'Stewart' from dual union all 
  select 'Omar', 'Carter' from dual union all 
  select 'Eldridge', 'Maxwell' from dual union all 
  select 'Cornelia', 'Daniels' from dual union all 
  select 'Elsa', 'Robbins' from dual union all 
  select 'Louella', 'May' from dual union all 
  select 'Gaylord', 'Arias' from dual union all 
  select 'April', 'Kennedy' from dual union all 
  select 'Kirk', 'Payne' from dual union all 
  select 'Marvin', 'Huff' from dual union all 
  select 'Sharon', 'Moreno' from dual union all 
  select 'Arthur', 'Oliver' from dual union all 
  select 'Rodolfo', 'Marsh' from dual union all 
  select 'Claude', 'Gaines' from dual union all 
  select 'Latisha', 'Jimenez' from dual union all 
  select 'Alfonso', 'Ruiz' from dual union all 
  select 'Lolita', 'Hardin' from dual union all 
  select 'Houston', 'Fletcher' from dual union all 
  select 'Francesco', 'Estes' from dual union all 
  select 'Latoya', 'Clay' from dual union all 
  select 'Lonny', 'Wagner' from dual union all 
  select 'Isabelle', 'Chung' from dual union all 
  select 'Maggie', 'Sloan' from dual union all 
  select 'Raymon', 'Kim' from dual union all 
  select 'Sabrina', 'Contreras' from dual union all 
  select 'Aurora', 'Miranda' from dual union all 
  select 'Etta', 'Shepard' from dual union all 
  select 'Janice', 'Barr' from dual union all 
  select 'Eduard', 'Uta' from dual union all 
  select 'Rachelle', 'Green' from dual union all 
  select 'Mikel', 'Esparza' from dual union all 
  select 'Val', 'Petersen' from dual union all 
  select 'Kristie', 'Fritz' from dual union all 
  select 'Darrell', 'Henderson' from dual union all 
  select 'Luigi', 'Stuart' from dual union all 
  select 'Leola', 'Allison' from dual union all 
  select 'Florine', 'Coffey' from dual union all 
  select 'Milan', 'Ramos' from dual union all 
  select 'Weston', 'Pena' from dual union all 
  select 'Keven', 'Macias' from dual union all 
  select 'Willie', 'Roach' from dual union all 
  select 'Diego', 'Copeland' from dual union all 
  select 'George', 'Vang' from dual union all 
  select 'Rene', 'Waller' from dual union all 
  select 'Aubrey', 'Wolfe' from dual union all 
  select 'Gwen', 'Kaiser' from dual union all 
  select 'Blair', 'Wilcox' from dual union all 
  select 'Marquis', 'Bradley' from dual union all 
  select 'Angelique', 'Jensen' from dual union all 
  select 'Delores', 'Hester' from dual union all 
  select 'Daisy', 'Horton' from dual union all 
  select 'Sherwood', 'Pham' from dual union all 
  select 'Salvador', 'Moses' from dual union all 
  select 'Gloria', 'Morrison' from dual union all 
  select 'Rena', 'Walter' from dual union all 
  select 'Eula', 'Bond' from dual union all 
  select 'Brady', 'Gibbs' from dual union all 
  select 'Jeanette', 'Cooley' from dual union all 
  select 'Dudley', 'Navarro' from dual union all 
  select 'Federico', 'Matthews' from dual union all 
  select 'Helene', 'Rivera' from dual union all 
  select 'Mitch', 'Berg' from dual union all 
  select 'Wilfred', 'Cameron' from dual union all 
  select 'Arturo', 'Chase' from dual union all 
  select 'Monroe', 'Ingram' from dual union all 
  select 'Rosalinda', 'Khan' from dual union all 
  select 'Ruben', 'Tucker' from dual union all 
  select 'Kristina', 'Roth' from dual union all 
  select 'Fernando', 'Terrell' from dual union all 
  select 'Kathleen', 'Stevens' from dual union all 
  select 'Grady', 'Farley' from dual union all 
  select 'Ernesto', 'Manning' from dual union all 
  select 'Lorraine', 'Moss' from dual union all 
  select 'Tyron', 'Hunt' from dual union all 
  select 'Domenic', 'Lyons' from dual union all 
  select 'Reva', 'Mejia' from dual union all 
  select 'Lyman', 'Shannon' from dual union all 
  select 'Austin', 'Wyatt' from dual union all 
  select 'Tisha', 'Mitchell' from dual union all 
  select 'Letitia', 'Blair' from dual union all 
  select 'Sofia', 'Fuentes' from dual union all 
  select 'Bridgett', 'Delacruz' from dual union all 
  select 'Maxwell', 'Banks' from dual union all 
  select 'Judy', 'Gates' from dual union all 
  select 'Elizabeth', 'Cervantes' from dual union all 
  select 'Doreen', 'Barber' from dual union all 
  select 'Boris', 'Benjamin' from dual union all 
  select 'Wilmer', 'Lin' from dual union all 
  select 'Jamey', 'Stevenson' from dual union all 
  select 'Wiley', 'Poole' from dual union all 
  select 'Audra', 'Estrada' from dual union all 
  select 'Archie', 'Adkins' from dual union all 
  select 'Claudette', 'Mckay' from dual union all 
  select 'Jack', 'Downs' from dual union all 
  select 'Earle', 'Simmons' from dual union all 
  select 'Ingrid', 'Conrad' from dual union all 
  select 'Wendi', 'Osborne' from dual union all 
  select 'Vincent', 'Davila' from dual union all 
  select 'Janis', 'Rice' from dual union all 
  select 'Derick', 'Perkins' from dual union all 
  select 'Eugene', 'Roberson' from dual union all 
  select 'Dante', 'Compton' from dual union all 
  select 'Lyndon', 'Atkins' from dual union all 
  select 'Sallie', 'Taylor' from dual
)
select distinct 
      a.first_name,  
      b.last_name,
      a.first_name || '.' || b.last_name || '@' || lower(substr(a.first_name, 1, 2) || substr(b.last_name, 1, 2)) || '.com' as email
from cte a
cross join cte b
order by dbms_random.value;

-- delete from random_people;
